'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BOTerritoryPricing.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iActivityCodeFrom.
        '''</summary>
        Friend ReadOnly Property Param_iActivityCodeFrom() As String
            Get
                Return ResourceManager.GetString("Param_iActivityCodeFrom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iActivityCodeTo.
        '''</summary>
        Friend ReadOnly Property Param_iActivityCodeTo() As String
            Get
                Return ResourceManager.GetString("Param_iActivityCodeTo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iCopiedBasColor.
        '''</summary>
        Friend ReadOnly Property Param_iCopiedBasColor() As String
            Get
                Return ResourceManager.GetString("Param_iCopiedBasColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iCopiedBasDetail.
        '''</summary>
        Friend ReadOnly Property Param_iCopiedBasDetail() As String
            Get
                Return ResourceManager.GetString("Param_iCopiedBasDetail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iCopiedBasNatural.
        '''</summary>
        Friend ReadOnly Property Param_iCopiedBasNatural() As String
            Get
                Return ResourceManager.GetString("Param_iCopiedBasNatural", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iCreateDate.
        '''</summary>
        Friend ReadOnly Property Param_iCreateDate() As String
            Get
                Return ResourceManager.GetString("Param_iCreateDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iCTEWhere.
        '''</summary>
        Friend ReadOnly Property Param_iCTEWhere() As String
            Get
                Return ResourceManager.GetString("Param_iCTEWhere", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iFreightMarkup.
        '''</summary>
        Friend ReadOnly Property Param_iFreightMarkup() As String
            Get
                Return ResourceManager.GetString("Param_iFreightMarkup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iHasTerrPrice.
        '''</summary>
        Friend ReadOnly Property Param_iHasTerrPrice() As String
            Get
                Return ResourceManager.GetString("Param_iHasTerrPrice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iItemDesc.
        '''</summary>
        Friend ReadOnly Property Param_iItemDesc() As String
            Get
                Return ResourceManager.GetString("Param_iItemDesc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iItemDesc_From.
        '''</summary>
        Friend ReadOnly Property Param_iItemDesc_From() As String
            Get
                Return ResourceManager.GetString("Param_iItemDesc_From", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iItemDesc_To.
        '''</summary>
        Friend ReadOnly Property Param_iItemDesc_To() As String
            Get
                Return ResourceManager.GetString("Param_iItemDesc_To", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iItemNo.
        '''</summary>
        Friend ReadOnly Property Param_iItemNo() As String
            Get
                Return ResourceManager.GetString("Param_iItemNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iItemNo_From.
        '''</summary>
        Friend ReadOnly Property Param_iItemNo_From() As String
            Get
                Return ResourceManager.GetString("Param_iItemNo_From", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iItemNo_To.
        '''</summary>
        Friend ReadOnly Property Param_iItemNo_To() As String
            Get
                Return ResourceManager.GetString("Param_iItemNo_To", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iItems.
        '''</summary>
        Friend ReadOnly Property Param_iItems() As String
            Get
                Return ResourceManager.GetString("Param_iItems", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iLastDate.
        '''</summary>
        Friend ReadOnly Property Param_iLastDate() As String
            Get
                Return ResourceManager.GetString("Param_iLastDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iOnPriceList.
        '''</summary>
        Friend ReadOnly Property Param_iOnPriceList() As String
            Get
                Return ResourceManager.GetString("Param_iOnPriceList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iPrcNatural.
        '''</summary>
        Friend ReadOnly Property Param_iPrcColor() As String
            Get
                Return ResourceManager.GetString("Param_iPrcColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iPrcDetail.
        '''</summary>
        Friend ReadOnly Property Param_iPrcDetailStain() As String
            Get
                Return ResourceManager.GetString("Param_iPrcDetailStain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iPrcLevelFromNOT USED.
        '''</summary>
        Friend ReadOnly Property Param_iPrcLevelFrom() As String
            Get
                Return ResourceManager.GetString("Param_iPrcLevelFrom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iPrcLevelToNOT USED.
        '''</summary>
        Friend ReadOnly Property Param_iPrcLevelTo() As String
            Get
                Return ResourceManager.GetString("Param_iPrcLevelTo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iPrcColor.
        '''</summary>
        Friend ReadOnly Property Param_iPrcRococo() As String
            Get
                Return ResourceManager.GetString("Param_iPrcRococo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iPrcLevelB.
        '''</summary>
        Friend ReadOnly Property Param_iPriceLevelB() As String
            Get
                Return ResourceManager.GetString("Param_iPriceLevelB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iProdCat_From.
        '''</summary>
        Friend ReadOnly Property Param_iProdCat_From() As String
            Get
                Return ResourceManager.GetString("Param_iProdCat_From", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iProdCat_To.
        '''</summary>
        Friend ReadOnly Property Param_iProdCat_To() As String
            Get
                Return ResourceManager.GetString("Param_iProdCat_To", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iProdCatDesc_From.
        '''</summary>
        Friend ReadOnly Property Param_iProdCatDesc_From() As String
            Get
                Return ResourceManager.GetString("Param_iProdCatDesc_From", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iProdCatDesc_To.
        '''</summary>
        Friend ReadOnly Property Param_iProdCatDesc_To() As String
            Get
                Return ResourceManager.GetString("Param_iProdCatDesc_To", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iProdCategory.
        '''</summary>
        Friend ReadOnly Property Param_iProdCategory() As String
            Get
                Return ResourceManager.GetString("Param_iProdCategory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iProductCategory.
        '''</summary>
        Friend ReadOnly Property Param_iProductCategory() As String
            Get
                Return ResourceManager.GetString("Param_iProductCategory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iRowState.
        '''</summary>
        Friend ReadOnly Property Param_iRowState() As String
            Get
                Return ResourceManager.GetString("Param_iRowState", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iSearchType.
        '''</summary>
        Friend ReadOnly Property Param_iSearchType() As String
            Get
                Return ResourceManager.GetString("Param_iSearchType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iShowOnlyActive.
        '''</summary>
        Friend ReadOnly Property Param_iShowOnlyActive() As String
            Get
                Return ResourceManager.GetString("Param_iShowOnlyActive", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iTerCode.
        '''</summary>
        Friend ReadOnly Property Param_iTerCode() As String
            Get
                Return ResourceManager.GetString("Param_iTerCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iTerDesc.
        '''</summary>
        Friend ReadOnly Property Param_iTerDesc() As String
            Get
                Return ResourceManager.GetString("Param_iTerDesc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iTerFrom.
        '''</summary>
        Friend ReadOnly Property Param_iTerFrom() As String
            Get
                Return ResourceManager.GetString("Param_iTerFrom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iTerrCode_NOTUSED.
        '''</summary>
        Friend ReadOnly Property Param_iTerrCode() As String
            Get
                Return ResourceManager.GetString("Param_iTerrCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iType.
        '''</summary>
        Friend ReadOnly Property Param_iType() As String
            Get
                Return ResourceManager.GetString("Param_iType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iWhere.
        '''</summary>
        Friend ReadOnly Property Param_iWhere() As String
            Get
                Return ResourceManager.GetString("Param_iWhere", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to tvpA4GLIdentity.
        '''</summary>
        Friend ReadOnly Property Param_tvpA4GLIdentity() As String
            Get
                Return ResourceManager.GetString("Param_tvpA4GLIdentity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to tvpItem_no.
        '''</summary>
        Friend ReadOnly Property Param_tvpItem_no() As String
            Get
                Return ResourceManager.GetString("Param_tvpItem_no", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to spARCustFreightMarkupList_MAS.
        '''</summary>
        Friend ReadOnly Property SP_spARCustFreightMarkupList_MAS() As String
            Get
                Return ResourceManager.GetString("SP_spARCustFreightMarkupList_MAS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to spDeleteItemsByA4GLIdentity.
        '''</summary>
        Friend ReadOnly Property SP_spDeleteItemsByA4GLIdentity() As String
            Get
                Return ResourceManager.GetString("SP_spDeleteItemsByA4GLIdentity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to spDeleteItemsByItem_noTVP.
        '''</summary>
        Friend ReadOnly Property SP_spDeleteItemsByItem_noTVP() As String
            Get
                Return ResourceManager.GetString("SP_spDeleteItemsByItem_noTVP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to spIMGetItemList_MAS.
        '''</summary>
        Friend ReadOnly Property SP_spIMGetItemList_MAS() As String
            Get
                Return ResourceManager.GetString("SP_spIMGetItemList_MAS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to spIMGetItemListAdvanced_MAS.
        '''</summary>
        Friend ReadOnly Property SP_spIMGetItemListAdvanced_MAS() As String
            Get
                Return ResourceManager.GetString("SP_spIMGetItemListAdvanced_MAS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to spIMGetItemLookup_MAS.
        '''</summary>
        Friend ReadOnly Property SP_spIMGetItemLookup_MAS() As String
            Get
                Return ResourceManager.GetString("SP_spIMGetItemLookup_MAS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to spIMGetItemLookup_NoTerritory_MAS.
        '''</summary>
        Friend ReadOnly Property SP_spIMGetItemLookup_NoTerritory_MAS() As String
            Get
                Return ResourceManager.GetString("SP_spIMGetItemLookup_NoTerritory_MAS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to spIMGetProdCatActiveItems_MAS.
        '''</summary>
        Friend ReadOnly Property SP_spIMGetProdCatActiveItems_MAS() As String
            Get
                Return ResourceManager.GetString("SP_spIMGetProdCatActiveItems_MAS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to spIMGetProductCategories_MAS.
        '''</summary>
        Friend ReadOnly Property SP_spIMGetProductCategories_MAS() As String
            Get
                Return ResourceManager.GetString("SP_spIMGetProductCategories_MAS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to spIMSaveItem_MAS.
        '''</summary>
        Friend ReadOnly Property SP_spIMSaveItem_MAS() As String
            Get
                Return ResourceManager.GetString("SP_spIMSaveItem_MAS", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
